language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install pytest-pep8"
  - "pip install pytest-flakes"
  - "pip install pytest-flask"
  - "cp ./app/config/default_config.py ./app/config/config.py"
# command to run tests
script:
  - py.test
